[tool.poetry]
name = "mathgame"
version = "0.1.0"
description = ""
authors = ["Viktor Bogutskii"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pygame = "^2.6.1"
gtts = "^2.5.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
